name: Src-Folder CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # C++ 语言
      - name: Compile all C++
        run: g++ -Wall -Wextra -std=c++17 -O2 src/*/*.cpp -o prog

      - name: Run
        run: ./prog